### ISSUE TITLE
"Kernel is not ready!" with Ipython 1.0.0

### ISSUE THREAD

**Issue by emase** [tkf/emacs-ipython-notebook#128]
## Check list
- [\* ] I read "Avoid standard Emacs traps" section in
  https://github.com/tkf/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [\* ] I checked that IPython works with the browser interface.
- [\* ] I checked that the problem was not due to badly compiled
  files.  Removing `*.elc` files from source directory of EIN and
  its dependencies did not solve the problem.
- [\* ] I checked that the libraries are loaded from intended place.
  (You can check the location in the "System info" section below)
## Description of the problem you have

When I try executing code from a cell, I get the error: ein: [warn] Kernel is not ready yet! (or closed already.)

Everything was fine until I upgraded my ipython from 0.13.1 to 1.0.0

Downgrading ipython from 1.0.0 to 0.13.2 and things work fine. I guess something changed at 1.0.0
## Steps to reproduce the problem
1. Run emacs. Open notebooklist. Open a new notebook
2. Type print "hello" and then select execute-cell
## Expected output

"hello"
## Your EIN configuration (in .emacs.d/init.el or somewhere else)

no idea
## Your IPython configuration
1. What is your IPython version? (run `ipython --version`):
   $ ipython --version
   1.0.0
2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
   ipython notebook --profile=nbserver
3. What is your IPython notebook port number or URL?:
   http://ghettosuperstar:8888
## Additional information (if any)

Upgraded ipython from 0.13.1 to 1.0.0 using pip install --upgrade ipython
Tried running ein to connect and received "Kernel is not ready yet!" error.
Used M-x package-list-package to update EIN and its dependencies.
Still get "Kernel is not ready yet!"
## System info:

``` cl
("EIN system info"
 :emacs-version "GNU Emacs 24.2.1 (i386-mingw-nt6.1.7601)
 of 2012-08-28 on MARVIN"
 :emacs-bzr-version nil
 :window-system w32
 :emacs-variant nil
 :os
 (:uname nil
     :lsb-release nil)
 :image-types
 (png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (png xpm xbm pbm)
 :request
 (:backend url-retrieve)
 :ein
 (:version "0.2.1alpha2"
       :source-dir "c:/cygwin/home/mason/.emacs.d/elpa/ein-20130710.2114/")
 :lib
 ((:name "websocket"
     :path "~/.emacs.d/elpa/websocket-20130803.1409/websocket.el"
     :featurep t
     :version-var websocket-version
     :version "1.1")
  (:name "request"
     :path "~/.emacs.d/elpa/request-20130526.1915/request.el"
     :featurep t
     :version-var request-version
     :version "0.2.0")
  (:name "auto-complete"
     :path "~/.emacs.d/elpa/auto-complete-20130724.1750/auto-complete.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "auto-complete"
     :path "~/.emacs.d/elpa/auto-complete-20130724.1750/auto-complete.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "popup"
     :path "~/.emacs.d/elpa/popup-20130708.2245/popup.el"
     :featurep t
     :version-var popup-version
     :version "0.5.0")
  (:name "fuzzy"
     :path "c:/Program Files/emacs-24.2/site-lisp/fuzzy.el"
     :featurep nil
     :version-var nil
     :version nil)
  (:name "python"
     :path "c:/Program Files/emacs-24.2/lisp/progmodes/python.elc"
     :featurep t
     :version-var nil
     :version nil)
  (:name "python-mode"
     :path "c:/Program Files/emacs-24.2/site-lisp/python-mode.el"
     :featurep nil
     :version-var nil
     :version nil)
  (:name "smartrep"
     :path "~/.emacs.d/elpa/smartrep-20130312.1839/smartrep.el"
     :featurep t
     :version-var nil
     :version nil)))
```

**Comment by tkf** [comment]
Please wait for a while.  See #131.

**Comment by bjodah** [comment]
Just wanted to confirm that I too am experiencing the same issue.

Thanks for EIN!

**Comment by ethanwhite** [comment]
The examples given here are working fine for me with IPython 1.1.0, Emacs 24.3.1, Ubuntu 13.10. It might be worth trying upgrading IPython again in case something was fixed/changed back in 1.1.

**Comment by emase** [comment]
Hmm... still getting the same error after upgrading.Upgraded setup: emacs 24.3.1 (with a clean MELPA install of ein) on Windows 7ipython 1.1 on Ubuntu 12.04
Originally was using emacs 24.2, but will keep 24.3.1 now that I have it setup. Both versions of emacs work correctly with ipython 0.13.2, but not with 1.0 or 1.1

Date: Thu, 7 Nov 2013 08:07:14 -0800

**Comment by ethanwhite** [comment]
Hmm... only differences seem to be Ubuntu version (unlikely) and that I installed EIN using [el-get](https://github.com/dimitri/el-get), not MELPA. I just checked this on another machine with the same setup and EIN is working there as well (at least the basic stuff).

**Comment by poneill** [comment]
Hi Takafumi,

Thanks for writing ein.  It's really impressive, and I'd like to make
it a permanent part of my workflow.  I'm having the same problem here.
I saw issue #131 and understand that it's on the backburner :), so I'm
including this bug report only because it seems like there's some
uncertainty about exactly which conditions trigger this bug. Perhaps 
another data point might be useful.

cheers,
Pat.

## Check list
- [YES ] I read "Avoid standard Emacs traps" section in
  https://github.com/tkf/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [YES ] I checked that IPython works with the browser interface.
- [YES ] I checked that the problem was not due to badly compiled
  files.  Removing `*.elc` files from source directory of EIN and
  its dependencies did not solve the problem.
- [YES] I checked that the libraries are loaded from intended place.
  (You can check the location in the "System info" section below)

## Description of the problem you have

[same deal as above]

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

in my init file:
...
(require 'ein)
...

## Your IPython configuration
1. What is your IPython version? (run `ipython --version`):

1.1.0
1. How do you start IPython? (e.g., `ipython notebook --port 9999`):

ipython notebook
1. What is your IPython notebook port number or URL?:

8888

## Additional information (if any)

I tried running zeroein.el, but received the message:

"Cannot open load file: websocket"

in my new emacs instance.

## System info:

``` cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.8.2)
 of 2013-07-26 on roseapple, modified by Debian"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux noether 3.11.0-20-generic #35-Ubuntu SMP Fri May 2 21:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:    13.10
Codename:   saucy
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.2.1alpha2"
       :source-dir "/home/pat/.emacs.d/elpa/ein-20140317.1114/")
 :lib
 ((:name "websocket"
     :path "~/.emacs.d/elpa/websocket-20140104.1438/websocket.el"
     :featurep t
     :version-var websocket-version
     :version "1.1")
  (:name "request"
     :path "~/.emacs.d/elpa/request-20140316.417/request.elc"
     :featurep t
     :version-var request-version
     :version "0.2.0")
  (:name "auto-complete"
     :path "~/.emacs.d/elpa/auto-complete-20140803.2118/auto-complete.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "auto-complete"
     :path "~/.emacs.d/elpa/auto-complete-20140803.2118/auto-complete.el"
     :featurep t
     :version-var nil
     :version nil)
  (:name "popup"
     :path "~/.emacs.d/elpa/popup-20140207.1702/popup.elc"
     :featurep t
     :version-var popup-version
     :version "0.5.0")
  (:name "python"
     :path "/usr/share/emacs/24.3/lisp/progmodes/python.elc"
     :featurep t
     :version-var nil
     :version nil)
  (:name "python-mode"
     :path "~/emacs-config/python-mode.el"
     :featurep nil
     :version-var nil
     :version nil)
  (:name "markdown-mode"
     :path "~/emacs-config/markdown-mode.el"
     :featurep t
     :version-var markdown-mode-version
     :version "2.0")))
```
